<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SqlAgent.Core.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SqlAgent.Core\SqlAgent.Core.csproj" />
  </ItemGroup>
</Project>
